// Git Integration for Beast CLI
// Implements Aider-style 6-flag attribution and Claude Code safety protocol

import { spawn } from 'node:child_process'
import { promisify } from 'node:util'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const execAsync = promisify(spawn)

export interface GitConfig {
  // Attribution flags (6-flag system)
  attributeAuthor: boolean      // GIT_AUTHOR_NAME
  attributeCommitter: boolean  // GIT_COMMITTER_NAME
  attributeCoAuthoredBy: boolean  // Co-authored-by trailer
  attributeCommitMessageAuthor: boolean  // Include in commit message author
  attributeCommitMessageCommitter: boolean  // Include in commit message committer

  // Other options
  autoCommit: boolean
  commitPrompt: string
  subtreeOnly: boolean
  gitCommitVerify: boolean  // Respect pre-commit hooks

  // User info
  userName: string
  userEmail: string
}

export interface CommitResult {
  success: boolean
  hash?: string
  message?: string
  error?: string
}

export interface DiffResult {
  staged: string[]
  unstaged: string[]
  untracked: string[]
  changed: string[]
}

// Default configuration
export const defaultGitConfig: GitConfig = {
  attributeAuthor: true,
  attributeCommitter: true,
  attributeCoAuthoredBy: false,
  attributeCommitMessageAuthor: false,
  attributeCommitMessageCommitter: false,
  autoCommit: false,
  commitPrompt: 'Auto-generated by Beast CLI',
  subtreeOnly: false,
  gitCommitVerify: true,
  userName: 'Beast CLI',
  userEmail: 'beast@cli.local',
}

// Check if directory is a git repo
export async function isGitRepo(cwd: string): Promise<boolean> {
  try {
    const result = await runGit(['rev-parse', '--git-dir'], cwd)
    return result.exitCode === 0
  } catch {
    return false
  }
}

// Get git root directory
export async function getGitRoot(cwd: string): Promise<string | null> {
  try {
    const result = await runGit(['rev-parse', '--show-toplevel'], cwd)
    if (result.exitCode === 0) {
      return result.stdout.trim()
    }
    return null
  } catch {
    return null
  }
}

// Run git command with environment variables
async function runGit(
  args: string[],
  cwd: string,
  env?: Record<string, string>
): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  return new Promise((resolve) => {
    const proc = spawn('git', args, {
      cwd,
      env: { ...process.env, ...env },
      shell: true,
    })

    let stdout = ''
    let stderr = ''

    proc.stdout?.on('data', (data) => { stdout += data.toString() })
    proc.stderr?.on('data', (data) => { stderr += data.toString() })

    proc.on('close', (code) => {
      resolve({ stdout, stderr, exitCode: code ?? 1 })
    })

    proc.on('error', (err) => {
      resolve({ stdout: '', stderr: err.message, exitCode: 1 })
    })
  })
}

// Get status of repository
export async function getStatus(cwd: string): Promise<DiffResult> {
  const result = await runGit(['status', '--porcelain=v1'], cwd)
  const lines = result.stdout.split('\n').filter(Boolean)

  const staged: string[] = []
  const unstaged: string[] = []
  const untracked: string[] = []
  const changed: string[] = []

  for (const line of lines) {
    const indexStatus = line[0]
    const workTreeStatus = line[1]
    const filePath = line.slice(3)

    if (indexStatus === '?' && workTreeStatus === '?') {
      untracked.push(filePath)
      changed.push(filePath)
    } else {
      if (indexStatus !== '.' && indexStatus !== ' ') {
        staged.push(filePath)
      }
      if (workTreeStatus !== '.' && workTreeStatus !== ' ') {
        unstaged.push(filePath)
      }
      changed.push(filePath)
    }
  }

  return { staged, unstaged, untracked, changed }
}

// Get diff for file
export async function getDiff(
  filePath: string,
  cwd: string,
  staged = false
): Promise<string> {
  const args = staged ? ['diff', '--staged', filePath] : ['diff', filePath]
  const result = await runGit(args, cwd)
  return result.stdout
}

// Get staged diff
export async function getStagedDiff(cwd: string): Promise<string> {
  const result = await runGit(['diff', '--staged'], cwd)
  return result.stdout
}

// Stage files
export async function stageFiles(files: string[], cwd: string): Promise<boolean> {
  if (files.length === 0) return true

  const result = await runGit(['add', ...files], cwd)
  return result.exitCode === 0
}

// Commit with attribution (6-flag system)
export async function commit(
  cwd: string,
  message: string,
  config: GitConfig,
  aiderEdits = true
): Promise<CommitResult> {
  // Build environment for attribution
  const env: Record<string, string> = {}

  if (aiderEdits) {
    // AI-generated changes
    if (config.attributeCoAuthoredBy) {
      // Co-authored-by takes precedence
      env['GIT_AUTHOR_NAME'] = config.userName
      env['GIT_AUTHOR_EMAIL'] = config.userEmail
      env['GIT_COMMITTER_NAME'] = config.userName
      env['GIT_COMMITTER_EMAIL'] = config.userEmail

      // Add trailer to message
      const model = 'claude-3.5-sonnet'  // Would be dynamic in real implementation
      message += `\n\nCo-authored-by: ${config.userName} <${model}> <beast@cli.local>`
    } else {
      // Default: modify author/committer names
      if (config.attributeAuthor) {
        env['GIT_AUTHOR_NAME'] = `${config.userName} (aider)`
        env['GIT_AUTHOR_EMAIL'] = 'aider@beast-cli.local'
      }
      if (config.attributeCommitter) {
        env['GIT_COMMITTER_NAME'] = `${config.userName} (aider)`
        env['GIT_COMMITTER_EMAIL'] = 'aider@beast-cli.local'
      }
    }
  } else {
    // User commit - respect pre-commit hooks, modify committer only
    if (config.attributeCommitter) {
      env['GIT_COMMITTER_NAME'] = `${config.userName} (aider)`
      env['GIT_COMMITTER_EMAIL'] = 'aider@beast-cli.local'
    }
    // Never modify author name for user commits
  }

  // Check for pre-commit hooks (never bypass)
  if (config.gitCommitVerify) {
    // Run pre-commit hooks
    const preCommitResult = await runGit(['commit', '--dry-run', '--no-verify'], cwd, env)
    if (preCommitResult.exitCode !== 0 && preCommitResult.stderr.includes('hook')) {
      return {
        success: false,
        error: 'Pre-commit hooks failed. Cannot bypass.',
      }
    }
  }

  // Create commit
  // Write message to temp file to handle multi-line messages
  const tempFile = resolve(cwd, '.beast-commit-msg')
  writeFileSync(tempFile, message)

  const result = await runGit(
    ['commit', '-F', '.beast-commit-msg'],
    cwd,
    env
  )

  // Clean up temp file
  try {
    const fs = require('node:fs')
    fs.unlinkSync(tempFile)
  } catch {}

  if (result.exitCode === 0) {
    // Get commit hash
    const hashResult = await runGit(['rev-parse', 'HEAD'], cwd, env)
    return {
      success: true,
      hash: hashResult.stdout.trim(),
      message,
    }
  }

  return {
    success: false,
    error: result.stderr || 'Commit failed',
  }
}

// Create ghost commit (detached commit for snapshots)
export async function createGhostCommit(
  cwd: string,
  message: string,
  config: GitConfig
): Promise<CommitResult> {
  // Get current tree
  const treeResult = await runGit(['write-tree'], cwd)
  if (treeResult.exitCode !== 0) {
    return { success: false, error: 'Failed to create tree' }
  }

  const tree = treeResult.stdout.trim()

  // Get parent commit (if any)
  const parentResult = await runGit(['rev-parse', 'HEAD'], cwd)
  const parent = parentResult.exitCode === 0 ? parentResult.stdout.trim() : null

  // Set up environment
  const env: Record<string, string> = {
    GIT_AUTHOR_NAME: `${config.userName} (beast-ghost)`,
    GIT_AUTHOR_EMAIL: 'ghost@beast-cli.local',
    GIT_COMMITTER_NAME: `${config.userName} (beast-ghost)`,
    GIT_COMMITTER_EMAIL: 'ghost@beast-cli.local',
  }

  // Create commit object
  const parentArg = parent ? ['-p', parent] : []
  const commitResult = await runGit(
    ['commit-tree', tree, '-m', message, ...parentArg],
    cwd,
    env
  )

  if (commitResult.exitCode === 0) {
    return {
      success: true,
      hash: commitResult.stdout.trim(),
      message: `Ghost commit: ${message}`,
    }
  }

  return {
    success: false,
    error: commitResult.stderr || 'Ghost commit failed',
  }
}

// Get commit history
export async function getLog(
  cwd: string,
  limit = 10
): Promise<Array<{ hash: string; message: string; author: string; date: string }>> {
  const result = await runGit(
    ['log', '--format=%H|%s|%an|%ad', `--max-count=${limit}`],
    cwd
  )

  if (result.exitCode !== 0) {
    return []
  }

  return result.stdout
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      const [hash, message, author, date] = line.split('|')
      return { hash, message, author, date }
    })
}

// Get diff stats
export async function getDiffStats(cwd: string): Promise<{
  insertions: number
  deletions: number
  files: number
}> {
  const result = await runGit(['diff', '--stat'], cwd)
  const lines = result.stdout.split('\n')

  let insertions = 0
  let deletions = 0
  let files = 0

  // Parse "file.js | 10 ++--"
  for (const line of lines) {
    if (line.includes('|')) {
      files++
      const match = line.match(/(\d+)\s+\+/g)
      if (match) {
        insertions += match.reduce((sum, m) => sum + parseInt(m), 0)
      }
      const delMatch = line.match(/(\d+)\s+-/g)
      if (delMatch) {
        deletions += delMatch.reduce((sum, m) => sum + parseInt(m), 0)
      }
    }
  }

  return { insertions, deletions, files }
}

// Check if file has uncommitted changes
export async function isFileDirty(filePath: string, cwd: string): Promise<boolean> {
  const relativePath = resolve(cwd, filePath)
  const result = await runGit(['diff', '--quiet', relativePath], cwd)
  return result.exitCode !== 0
}

// Get branch name
export async function getBranch(cwd: string): Promise<string> {
  const result = await runGit(['branch', '--show-current'], cwd)
  return result.exitCode === 0 ? result.stdout.trim() : 'unknown'
}

export default {
  isGitRepo,
  getGitRoot,
  getStatus,
  getDiff,
  getStagedDiff,
  stageFiles,
  commit,
  createGhostCommit,
  getLog,
  getDiffStats,
  isFileDirty,
  getBranch,
  defaultGitConfig,
}